# Generated by Django 3.1 on 2022-02-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220224_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_jointed',
            new_name='date_joined',
        ),
    ]
